### ISSUE TITLE
拓展简单机器

### ISSUE THREAD

**Issue by haiman233** [SlimefunReloadingProject/RykenSlimeCustomizer#13]
食品加工机、加热压力舱、电动坩埚、压缩机、自动附魔机和祛魔机、附魔书整合机、自动铁砧、自动烘干机、自动酿造机、炼油机、自动喂食机、食品堆肥机、冰箱、流体泵、碳压机、全自动收集机、铁傀儡和凋灵装配机

**Comment by lijinhong11** [comment]
😰

**Comment by haiman233** [comment]
食品堆肥机啊，有机食品加工成有机肥料，粘液原版的，我海曼科技还用到了

**Comment by haiman233** [comment]
![4_EKZ8K`20AVNA%TL30@`3R](https://github.com/SlimefunReloadingProject/RykenSlimeCustomizer/assets/83174104/6cb7dc4b-8487-462f-a985-f5348dab5c11)

**Comment by lijinhong11** [comment]
基本完毕，1.4发布会关闭issue

**Comment by JWJUN233233** [comment]
现在更简单 直接super就行了
