### ISSUE TITLE
建议 添加超链接物品

### ISSUE THREAD

**Issue by haiman233** [SlimefunReloadingProject/RykenSlimeCustomizer#32]
类似于无尽里的一个指向wiki的物品，点击这个物品会退出粘液书并在聊天框内显示一段链接，玩家可以点击链接转到wiki

**Comment by balugaq** [comment]
![b91c584e85ce597615faa7ed377375f6](https://github.com/SlimefunReloadingProject/RykenSlimeCustomizer/assets/129668183/981139bf-7a28-406f-a330-1581ea601f67)
这种？

**Comment by lijinhong11** [comment]
要这玩意干甚 而且有时候不起作用

**Comment by balugaq** [comment]
bump那种wiki分类已经实现了，可以用那种

**Comment by haiman233** [comment]
> 要这玩意干甚 而且有时候不起作用

就是粘液书里一个物品用来链接到wiki方便玩家找教程

**Comment by lijinhong11** [comment]
no 这玩意还要魔改gui :(

**Comment by haiman233** [comment]
等一下，我忘了哪个附属里有了，

**Comment by balugaq** [comment]
emm

**Comment by balugaq** [comment]
> bump那种wiki分类已经实现了，可以用那种

**Comment by haiman233** [comment]
哦对，就是bump的wiki分类，点一下就会跳一个链接出来

**Comment by balugaq** [comment]
无尽那种每个物品单独wiki更麻烦点吧

**Comment by balugaq** [comment]
bump的已经实现了，你可以去看最新的示例

**Comment by balugaq** [comment]
可以close了

**Comment by haiman233** [comment]
> bump的已经实现了，你可以去看最新的示例
实现啥？
