### ISSUE TITLE
物品nbt混淆/错误残留

### ISSUE THREAD

**Issue by haiman233** [SlimefunReloadingProject/RykenSlimeCustomizer#36]
1、首先，用保存物品功能保存了15种不同等级的光
2、将这些不同等级的光全部注册为粘液物品
3、在机器的输入输出中正确引用这些物品(是slimefun物品，如果直接引用saveditem的话在无论在sc还是在rsc都会出现此bug)、书本内显示的输入输出均正确，点击相应的保存物品均能正确跳转配方（我写的输入输出是0级光制作1级光，1级光制作2级光以此类推）
4、结果无论是机器产出还是高级工作台合成均会出现混淆(0级光产出1级光，1级光产出1级光，2级光产出1级光，即使14极光对应的产出物品是一个原版物品，仍旧产出1级光)
在sc中，把每个光注册为粘液物品再引用，问题就解决了，但是在rsc中，即使注册为粘液物品，仍然会出现上述bug

似乎成书和烟花也会出现上述混淆nbt的bug，画暂时没测试过，药水不会有这bug（可能是因为涉及的nbt比较多）

**Comment by haiman233** [comment]
我给个视频演示，这是在我将机器输入输出改成直接用高级工作台合成后发现仍然存在此问题

**Comment by haiman233** [comment]
[QQ录屏20240622211047.zip](https://github.com/user-attachments/files/15936653/QQ.20240622211047.zip)
压缩了一下

**Comment by lijinhong11** [comment]
9

**Comment by haiman233** [comment]
我卡了一下页面，拿出来的东西里面slimefun的nbt都在

**Comment by lijinhong11** [comment]
剩下一半由粘液处理
