### ISSUE TITLE
重载指令导致研究解锁进度丢失

### ISSUE THREAD

**Issue by Hikari16665** [SlimefunReloadingProject/RykenSlimeCustomizer#37]
1.在服务器启动好后，解锁一些研究
2.解锁研究后输入/rsc reload
3.RSC注册的所有研究进度丢失。

**Comment by lijinhong11** [comment]
首先重载后研究会一同disable，这个我也不好说该不该disable
其次你重载绝对会丢研究，我的建议是能不必要重载就不重载

**Comment by lijinhong11** [comment]
这个问题我只能选择close

**Comment by Hikari16665** [comment]
可否在/rsc reload指令后面添加可选参数指定需要重载的addon，如果不指定就是全局重载，重载的addon如果被其他addon依赖就一起重载
