### ISSUE TITLE
薛定谔的多方块机器

### ISSUE THREAD

**Issue by haiman233** [SlimefunReloadingProject/RykenSlimeCustomizer#50]
简述：就是很玄乎，我也不知道是哪个方块导致的或者是哪个方块出了问题，如视频
[QQ20241020-235439.zip](https://github.com/user-attachments/files/17451013/QQ20241020-235439.zip)

**Comment by haiman233** [comment]
正常的多方块机器点了工作方块是会有字跳出来，而有问题的不会有字跳出来也不会工作，但是工作方块是能识别的（表现为拿方块对着工作方块右键，放不了方块（如果是搭错了，不会有放不了方块的情况））

**Comment by haiman233** [comment]
[WorldTaste.zip](https://github.com/user-attachments/files/17451019/WorldTaste.zip)
配置文件

**Comment by haiman233** [comment]
知道问题了，工作方块必须在发射器头上（需要在wiki里补充一下）

**Comment by balugaq** [comment]
解决了就可以close了 :)
