### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by haiman233** [SlimefunReloadingProject/RykenSlimeCustomizer#9]
自定义类似于人造钻石一样的可以直接在原版工作台充当普通钻石合成用的物品和类似于彩虹羊毛的物品（我记得我以前往粘液的api里头添加过其它彩虹方块，但是没有人引用过）（可以加到物品通用格式里）
通用物品格式-灵魂绑定、背包、（方块）防凋灵
自定义装备（不知道可不可以合并到通用物品格式），ProtectionType（包括防辐射、防蜜蜂、防动能），斩首吸血之类的
自定义猪灵交易物品（类似于奇怪的下界粘液）
自定义挖掘方块概率掉落物品（类似于打草掉种子的那种）
自定义机器人（可以改一些效率，燃料啥）
自定义有核反应堆机制和类似于铁傀儡装配机的机器
拓展simplemachines的机器类型（做有机食品的机器和加速器类机器https://slimefun.github.io/javadocs/Slimefun4/docs/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/accelerators/package-summary.html）
自定义多方块机器的电动版，比如说拥有古老的祭坛配方的电动祭坛

**Comment by lijinhong11** [comment]
通用物品格式塞不了nbt

**Comment by haiman233** [comment]
> 通用物品格式塞不了nbt

那灵魂绑定、背包、（方块）防凋灵这些呢

**Comment by lijinhong11** [comment]
> > 通用物品格式塞不了nbt
> 
> 那灵魂绑定、背包、（方块）防凋灵这些呢
> 

背包用保存物品实现 其余的我想想

**Comment by balugaq** [comment]
| NUMBER | ITEM | STATUS | TESTED? | DESCRIPTION |
| - | - | - | - | - |
| 1 | 人造物品 | √ | √
| 2 | 彩虹方块 | √ | √
| 3 | 灵魂绑定 | √ | √
| 4 | 防凋灵方块 | √ | √
| 5 | 自定义装备 | √ |√
| 6 | 装备ProtectionType（包括防辐射、防蜜蜂、防动能） | √ | ×
| 7 | 自定义猪灵交易物品 | √ | √
| 8 | 自定义挖掘方块概率掉落物品 | √ | √
| 9 | 拓展simple_machines的机器类型（加速器） | √ | √
| 10 | 自定义多方块机器的电动版 | √ | × | 可使用配方机器实现
| 11 | 自定义背包 | √ | × | 可使用保存物品实现
| 12 | 自定义有核反应堆机制和类似于铁傀儡装配机的机器 | √ | × | 可使用机器自定义tick实现
| 13 | 自定义机器人（可以改一些效率，燃料） | × | × | 继承物品应该可以实现？
| 14 | 武器斩首吸血 | × | × | 继承物品应该可以实现？

**Comment by lijinhong11** [comment]
> NUMBER	ITEM	STATUS	TESTED?	DESCRIPTION
> 1	人造物品	√	√	
> 2	彩虹方块	√	√	
> 3	灵魂绑定	√	√	
> 4	防凋灵方块	√	√	
> 5	自定义装备	√	√	
> 6	装备ProtectionType（包括防辐射、防蜜蜂、防动能）	√	×	
> 7	自定义猪灵交易物品	√	√	
> 8	自定义挖掘方块概率掉落物品	√	√	
> 9	拓展simple_machines的机器类型（加速器）	√	√	
> 10	自定义多方块机器的电动版	√	×	可使用配方机器实现
> 11	自定义背包	√	×	可使用保存物品实现
> 12	自定义有核反应堆机制和类似于铁傀儡装配机的机器	√	×	可使用机器自定义tick实现
> 13	自定义机器人（可以改一些效率，燃料）	×	×	继承物品应该可以实现？
> 14	武器斩首吸血	×	×	继承物品应该可以实现？

对于自定义机器人， 一部分东西基本是写死的，而且添加自定义燃料貌似没多大意义（？ 不一定会复出
对于武器斩首吸血，这玩意就是做一个脚本的事，不过武器左键还没实现，未来有
